config/routes.rb
Shoppe::Engine.routes.draw do

  get 'attachment/:id/:filename.:extension' => 'attachments#show'

  resources :customers do
    post :search, :on => :collection
    resources :addresses
  end
  
  resources :product_categories do
    resources :localisations, controller: "product_category_localisations"
  end
  resources :products do
    resources :variants
    resources :localisations, controller: "product_localisations"
    collection do
      get :import
      post :import
    end
  end
  resources :orders do
    collection do
      post :search
    end
    member do
      post :accept
      post :reject
      post :ship
      get :despatch_note
    end
    resources :payments, :only => [:create, :destroy] do
      match :refund, :on => :member, :via => [:get, :post]
    end
  end
  resources :stock_level_adjustments, :only => [:index, :create]
  resources :delivery_services do
    resources :delivery_service_prices
  end
  resources :tax_rates
  resources :users
  resources :countries
  resources :attachments, :only => :destroy

  get 'settings'=> 'settings#edit'
  post 'settings' => 'settings#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  match 'login/reset' => 'sessions#reset', :via => [:get, :post]

  delete 'logout' => 'sessions#destroy'
  root :to => 'dashboard#home'
end

app/models/shoppe/address.rb
module Shoppe
  class Address < ActiveRecord::Base

    # An array of all the available types for an address
    TYPES = ["billing", "delivery"]

    # Set the table name
    self.table_name = "shoppe_addresses"
    
    # The customer which this address should be linked to
    # 
    # @return [Shoppe::Customer]
    belongs_to :customer, :class_name => "Shoppe::Customer"
    
    # The order which this address should be linked to
    # 
    # @return [Shoppe::Order]
    belongs_to :order, :class_name => "Shoppe::Order"

    # The country which this address should be linked to
    #
    # @return [Shoppe::Country]
    belongs_to :country, :class_name => "Shoppe::Country"

    # Validations
    validates :address_type, :presence => true, :inclusion => {:in => TYPES}
    validates :address1, :presence => true
    validates :address3, :presence => true
    validates :address4, :presence => true
    validates :postcode, :presence => true
    validates :country, :presence => true

    # All addresses ordered by their id asending
    scope :ordered, -> { order(:id => :desc)}
    scope :default, -> { where(default: true)}
    scope :billing, -> { where(address_type: "billing")}
    scope :delivery, -> { where(address_type: "delivery")}

    def full_address
      [address1, address2, address3, address4, postcode, country.try(:name)].join(", ")
    end

  end
end

app/models/shoppe/attachment.rb
module Shoppe
  class Attachment < ActiveRecord::Base

    # Set the table name
    self.table_name = "shoppe_attachments"

    # Mount the Carrierwave uploader
    mount_uploader :file, AttachmentUploader

    # Relationships
    belongs_to :parent, :polymorphic => true

    # Validations
    validates :file_name, :presence => true
    validates :file_type, :presence => true
    validates :file_size, :presence => true
    validates :file, :presence => true
    validates :token, :presence => true, :uniqueness => true

    # All attachments should have a token assigned to this
    before_validation { self.token = SecureRandom.uuid if self.token.blank? }

    # Set the appropriate values in the model
    before_validation do
      if self.file
        self.file_name = self.file.filename if self.file_name.blank?
        self.file_type = self.file.content_type if self.file_type.blank?
        self.file_size = self.file.size if self.file_size.blank?
      end
    end

    # Return the attachment for a given role
    def self.for(role)
      self.where(:role => role).first
    end

    # Return the path to the attachment
    def path
      file.url
    end

    # Is the attachment an image?
    def image?
      file_type.match(/\Aimage\//).present?
    end
    
  end
end

app/models/shoppe/country.rb
module Shoppe
  
  # The Shoppe::Country model stores countries which can be used for delivery & billing
  # addresses for orders.
  #
  # You can use the Shoppe::CountryImporter to import a pre-defined list of countries 
  # into your database. This automatically happens when you run the 'shoppe:setup' 
  # rake task.
  
  class Country < ActiveRecord::Base
    
    self.table_name = 'shoppe_countries'
    
    # All orders which have this country set as their billing country
    has_many :billed_orders, :dependent => :restrict_with_exception, :class_name => 'Shoppe::Order', :foreign_key => 'billing_country_id'
    
    # All orders which have this country set as their delivery country
    has_many :delivered_orders, :dependent => :restrict_with_exception, :class_name => 'Shoppe::Order', :foreign_key => 'delivery_country_id'
    
    # All countries ordered by their name asending
    scope :ordered, -> { order(:name => :asc) }
    
    # Validations
    validates :name, :presence => true
    
  end
end

app/models/shoppe/customer.rb
module Shoppe
  class Customer < ActiveRecord::Base

    self.table_name = "shoppe_customers"

    has_many :addresses, :dependent => :restrict_with_exception, :class_name => "Shoppe::Address"

    has_many :orders, :dependent => :restrict_with_exception, :class_name => "Shoppe::Order"

    # Validations
    validates :email, :presence => true, :uniqueness => true, :format => {:with => /\A\b[A-Z0-9\.\_\%\-\+]+@(?:[A-Z0-9\-]+\.)+[A-Z]{2,6}\b\z/i}
    validates :phone, :presence => true, :format => {:with => /\A[+?\d\ \-x\(\)]{7,}\z/}

    # All customers ordered by their ID desending
    scope :ordered, -> { order(:id => :desc)}

    # The name of the customer in the format of "Company (First Last)" or if they don't have
    # company specified, just "First Last".
    #
    # @return [String]
    def name
      company.blank? ? full_name : "#{company} (#{full_name})"
    end

    # The full name of the customer created by concatinting the first & last name
    #
    # @return [String]
    def full_name
      "#{first_name} #{last_name}"
    end

    def self.ransackable_attributes(auth_object = nil) 
      ["id", "first_name", "last_name", "company", "email", "phone", "mobile"] + _ransackers.keys
    end
  
    def self.ransackable_associations(auth_object = nil)
      []
    end

  end
end

app/models/shoppe/delivery_service.rb
module Shoppe
  class DeliveryService < ActiveRecord::Base
  
    self.table_name = 'shoppe_delivery_services'

    # Validations
    validates :name, :presence => true
    validates :courier, :presence => true
  
    # Orders which are assigned to this delivery service
    has_many :orders, :dependent => :restrict_with_exception, :class_name => 'Shoppe::Order'
    
    # Prices for the different levels of service within this delivery service
    has_many :delivery_service_prices, :dependent => :destroy, :class_name => 'Shoppe::DeliveryServicePrice'
  
    # All active delivery services
    scope :active, -> { where(:active => true)}
    
    # Returns a tracking URL for the passed order
    #
    # @param order [Shoppe::Order]
    # @return [String] the full URL for the order.
    def tracking_url_for(order)
      return nil if self.tracking_url.blank?
      tracking_url = self.tracking_url.dup
      tracking_url.gsub!("{{consignment_number}}", CGI.escape(order.consignment_number.to_s))
      tracking_url.gsub!("{{delivery_postcode}}", CGI.escape(order.delivery_postcode.to_s))
      tracking_url.gsub!("{{billing_postcode}}", CGI.escape(order.billing_postcode.to_s))
      tracking_url
    end

  end
end

app/models/shoppe/delivery_service_price.rb
module Shoppe
  class DeliveryServicePrice < ActiveRecord::Base

    # Set the table name
    self.table_name = 'shoppe_delivery_service_prices'
  
    include Shoppe::AssociatedCountries
  
    # The delivery service which this price belongs to
    belongs_to :delivery_service, :class_name => 'Shoppe::DeliveryService'
    
    # The tax rate which should be applied
    belongs_to :tax_rate, :class_name => "Shoppe::TaxRate"
    
    # Validations
    validates :code, :presence => true
    validates :price, :numericality => true
    validates :cost_price, :numericality => true, :allow_blank => true
    validates :min_weight, :numericality => true
    validates :max_weight, :numericality => true
  
    # All prices ordered by their price ascending
    scope :ordered, -> { order(:price => :asc) }
    
    # All prices which are suitable for the weight passed.
    #
    # @param weight [BigDecimal] the weight of the order
    scope :for_weight, -> weight { where("min_weight <= ? AND max_weight >= ?", weight, weight) }
  
  end
end

app/models/shoppe/order.rb
module Shoppe
  class Order < ActiveRecord::Base

    self.table_name = 'shoppe_orders'

    # Orders can have properties
    key_value_store :properties

    # Require dependencies
    require_dependency 'shoppe/order/states'
    require_dependency 'shoppe/order/actions'
    require_dependency 'shoppe/order/billing'
    require_dependency 'shoppe/order/delivery'

    # All items which make up this order
    has_many :order_items, :dependent => :destroy, :class_name => 'Shoppe::OrderItem', :inverse_of => :order
    accepts_nested_attributes_for :order_items, :allow_destroy => true, :reject_if => Proc.new { |a| a['ordered_item_id'].blank? }

    # All products which are part of this order (accessed through the items)
    has_many :products, :through => :order_items, :class_name => 'Shoppe::Product', :source => :ordered_item, :source_type => 'Shoppe::Product'

    # The order can belong to a customer
    belongs_to :customer, :class_name => 'Shoppe::Customer'
    has_many :addresses, :through => :customers, :class_name => "Shoppe::Address"

    # Validations
    validates :token, :presence => true
    with_options :if => Proc.new { |o| !o.building? } do |order|
      order.validates :email_address, :format => {:with => /\A\b[A-Z0-9\.\_\%\-\+]+@(?:[A-Z0-9\-]+\.)+[A-Z]{2,6}\b\z/i}
      order.validates :phone_number, :format => {:with => /\A[+?\d\ \-x\(\)]{7,}\z/}
    end

    # Set some defaults
    before_validation { self.token = SecureRandom.uuid  if self.token.blank? }

    # Some methods for setting the billing & delivery addresses
    attr_accessor :save_addresses, :billing_address_id, :delivery_address_id

    # The order number
    #
    # @return [String] - the order number padded with at least 5 zeros
    def number
      id ? id.to_s.rjust(6, '0') : nil
    end

    # The length of time the customer spent building the order before submitting it to us.
    # The time from first item in basket to received.
    #
    # @return [Float] - the length of time
    def build_time
      return nil if self.received_at.blank?
      self.created_at - self.received_at
    end

    # The name of the customer in the format of "Company (First Last)" or if they don't have
    # company specified, just "First Last".
    #
    # @return [String]
    def customer_name
      company.blank? ? full_name : "#{company} (#{full_name})"
    end

    # The full name of the customer created by concatinting the first & last name
    #
    # @return [String]
    def full_name
      "#{first_name} #{last_name}"
    end

    # Is this order empty? (i.e. doesn't have any items associated with it)
    #
    # @return [Boolean]
    def empty?
      order_items.empty?
    end

    # Does this order have items?
    #
    # @return [Boolean]
    def has_items?
      total_items > 0
    end

    # Return the number of items in the order?
    #
    # @return [Integer]
    def total_items
      order_items.inject(0) { |t,i| t + i.quantity }
    end

    def self.ransackable_attributes(auth_object = nil)
      ["id", "billing_postcode", "billing_address1", "billing_address2", "billing_address3", "billing_address4", "first_name", "last_name", "company", "email_address", "phone_number", "consignment_number", "status", "received_at"] + _ransackers.keys
    end

    def self.ransackable_associations(auth_object = nil)
      []
    end

  end
end

app/models/shoppe/order/actions.rb
module Shoppe
  class Order < ActiveRecord::Base
    
    extend ActiveModel::Callbacks
    
    # These additional callbacks allow for applications to hook into other
    # parts of the order lifecycle.
    define_model_callbacks :confirmation, :acceptance, :rejection
  
    # This method should be called by the base application when the user has completed their 
    # first round of entering details. This will mark the order as "confirming" which means
    # the customer now just must confirm.
    #
    # @param params [Hash] a hash of order attributes
    # @return [Boolean]
    def proceed_to_confirm(params = {})
      self.status = 'confirming'
      if self.update(params)
        true
      else
        false
      end
    end
  
    # This method should be executed by the application when the order should be completed
    # by the customer. It will raise exceptions if anything goes wrong or return true if
    # the order has been confirmed successfully
    #
    # @return [Boolean]
    def confirm!
      no_stock_of = self.order_items.select(&:validate_stock_levels)
      unless no_stock_of.empty?
        raise Shoppe::Errors::InsufficientStockToFulfil, :order => self, :out_of_stock_items => no_stock_of
      end
    
      run_callbacks :confirmation do
        # If we have successfully charged the card (i.e. no exception) we can go ahead and mark this
        # order as 'received' which means it can be accepted by staff.
        self.status = 'received'
        self.received_at = Time.now
        self.save!

        self.order_items.each(&:confirm!)

        # Send an email to the customer
        deliver_received_order_email
      end
    
      # We're all good.
      true
    end
  
    # Mark order as accepted
    #
    # @param user [Shoppe::User] the user who carried out this action    
    def accept!(user = nil)
      run_callbacks :acceptance do
        self.accepted_at = Time.now
        self.accepter = user if user
        self.status = 'accepted'
        self.save!
        self.order_items.each(&:accept!)
        deliver_accepted_order_email
      end
    end
  
    # Mark order as rejected
    #
    # @param user [Shoppe::User] the user who carried out the action
    def reject!(user = nil)
      run_callbacks :rejection do
        self.rejected_at = Time.now
        self.rejecter = user if user
        self.status = 'rejected'
        self.save!
        self.order_items.each(&:reject!)
        deliver_rejected_order_email
      end
    end

    def deliver_accepted_order_email
      Shoppe::OrderMailer.accepted(self).deliver_now
    end

    def deliver_rejected_order_email
      Shoppe::OrderMailer.rejected(self).deliver_now
    end

    def deliver_received_order_email
      Shoppe::OrderMailer.received(self).deliver_now
    end
    
  end
end

app/models/shoppe/order/billing.rb
module Shoppe
  class Order < ActiveRecord::Base

    # The country which this order should be billed to
    #
    # @return [Shoppe::Country]
    belongs_to :billing_country, :class_name => 'Shoppe::Country', :foreign_key => 'billing_country_id'

    # Payments which have been stored for the order
    has_many :payments, :dependent => :destroy, :class_name => 'Shoppe::Payment'

    # Validations
    with_options :if => Proc.new { |o| !o.building? } do |order|
      order.validates :first_name, :presence => true
      order.validates :last_name, :presence => true
      order.validates :billing_address1, :presence => true
      order.validates :billing_address3, :presence => true
      order.validates :billing_address4, :presence => true
      order.validates :billing_postcode, :presence => true
      order.validates :billing_country, :presence => true
    end

    # The name for billing purposes
    #
    # @return [String]
    def billing_name
      company.blank? ? full_name : "#{full_name} (#{company})"
    end

    # The total cost of the order
    #
    # @return [BigDecimal]
    def total_cost
      self.delivery_cost_price +
      order_items.inject(BigDecimal(0)) { |t, i| t + i.total_cost }
    end

    # Return the price for the order
    #
    # @return [BigDecimal]
    def profit
      total_before_tax - total_cost
    end

    # The total price of all items in the basket excluding delivery
    #
    # @return [BigDecimal]
    def items_sub_total
      order_items.inject(BigDecimal(0)) { |t, i| t + i.sub_total }
    end

    # The total price of the order before tax
    #
    # @return [BigDecimal]
    def total_before_tax
      self.delivery_price + self.items_sub_total
    end

    # The total amount of tax due on this order
    #
    # @return [BigDecimal]
    def tax
      self.delivery_tax_amount +
      order_items.inject(BigDecimal(0)) { |t, i| t + i.tax_amount }
    end

    # The total of the order including tax
    #
    # @return [BigDecimal]
    def total
      self.delivery_price +
      self.delivery_tax_amount +
      order_items.inject(BigDecimal(0)) { |t, i| t + i.total }
    end

    # The total amount due on the order
    #
    # @return [BigDecimal]
    def balance
      @balance ||= total - amount_paid
    end

    # Is there a payment still outstanding on this order?
    #
    # @return [Boolean]
    def payment_outstanding?
      balance > BigDecimal(0)
    end

    # Has this order been paid in full?
    #
    # @return [Boolean]
    def paid_in_full?
      !payment_outstanding?
    end

    # Is the order invoiced?
    #
    # @return [Boolean]
    def invoiced?
      !invoice_number.blank?
    end

  end
end

app/views/shoppe/orders/_form.html.haml
= field_set_tag t('shoppe.orders.billing_address') do
  %dl
    %dt= f.label :customer_id, t('shoppe.orders.customer')
    %dd= f.collection_select :customer_id, Shoppe::Customer.ordered, :id, :name, {:include_blank => true}, {:data => {:placeholder => t('shoppe.orders.select_customer')}}
  .splitContainer
    %dl.third
      %dt= f.label :first_name, t('shoppe.orders.first_name')
      %dd= f.text_field :first_name, :class => 'focus text'
    %dl.third
      %dt= f.label :last_name, t('shoppe.orders.last_name')
      %dd= f.text_field :last_name, :class => 'text'
    %dl.third
      %dt= f.label :company, t('shoppe.orders.company')
      %dd= f.text_field :company, :class => 'text'
  %dl
    %dt= f.label :billing_address1, t('shoppe.orders.address')
    %dd.space= f.text_field :billing_address1, :class => 'text'
    %dd.space= f.text_field :billing_address2, :class => 'text'
    %dd.space= f.text_field :billing_address3, :class => 'text'
    %dd.space= f.text_field :billing_address4, :class => 'text'
  .splitContainer
    %dl.half
      %dt= f.label :billing_postcode, t('shoppe.orders.post_code')
      %dd= f.text_field :billing_postcode, :class => 'text'
    %dl.half
      %dt= f.label :billing_country_id, t('shoppe.orders.country')
      %dd= f.collection_select :billing_country_id, Shoppe::Country.ordered, :id, :name, {:include_blank => true}, {:data => {:placeholder => t('shoppe.orders.select_country')}}

  .splitContainer
    %dl.third
      %dt= f.label :email_address, t('shoppe.orders.email_address')
      %dd= f.text_field :email_address, :class => 'text'
    %dl.third
      %dt= f.label :phone_number, t('shoppe.orders.phone_number')
      %dd= f.text_field :phone_number, :class => 'text'
    %dl.third
      %dt= f.label :separate_delivery_address, t('shoppe.orders.separate_delivery_address')
      %dd.checkbox
        = f.check_box :separate_delivery_address
        = f.label :separate_delivery_address, t('shoppe.orders.use_separate_delivery_address?')

= field_set_tag t('shoppe.orders.delivery_address'), :class => 'delivery' do
  %dl
    %dt= f.label :delivery_name, t('shoppe.orders.delivery_name')
    %dd= f.text_field :delivery_name, :class => 'text'
  %dl
    %dt= f.label :delivery_address1, t('shoppe.orders.address')
    %dd.space= f.text_field :delivery_address1, :class => 'text'
    %dd.space= f.text_field :delivery_address2, :class => 'text'
    %dd.space= f.text_field :delivery_address3, :class => 'text'
    %dd.space= f.text_field :delivery_address4, :class => 'text'
  .splitContainer
    %dl.half
      %dt= f.label :delivery_postcode, t('shoppe.orders.post_code')
      %dd= f.text_field :delivery_postcode, :class => 'text'
    %dl.half
      %dt= f.label :delivery_country_id, t('shoppe.orders.country')
      %dd= f.collection_select :delivery_country_id, Shoppe::Country.ordered, :id, :name, {:include_blank => true}, {:data => {:placeholder => t('shoppe.orders.select_country')}}

app/views/shoppe/orders/_order_details.html.haml
.details
  .left
    %dl
      %dt= t('shoppe.orders.name')
      %dd= @order.full_name
      %dt= t('shoppe.orders.company')
      %dd= @order.company.blank? ? '-' : @order.company
      %dt
        - if @order.separate_delivery_address?
          = t('shoppe.orders.billing_address')
        - else
          = t('shoppe.orders.billing_delivery_address')

      %dd= @order.billing_address1
      %dd= @order.billing_address2
      %dd= @order.billing_address3
      %dd= @order.billing_address4
      %dd= @order.billing_postcode
      %dd= @order.billing_country.try(:name)
      - if @order.separate_delivery_address?
        %dt= t('shoppe.orders.delivery_address')
        %dd= @order.delivery_name
        %dd= @order.delivery_address1
        %dd= @order.delivery_address2
        %dd= @order.delivery_address3
        %dd= @order.delivery_address4
        %dd= @order.delivery_postcode
        %dd= @order.delivery_country.try(:name)
  .right
    %dl
      %dt= t('shoppe.orders.email_address')
      %dd= mail_to @order.email_address
      %dt= t('shoppe.orders.telephone')
      %dd= @order.phone_number
      %dt= t('shoppe.orders.weight')
      %dd= number_to_weight @order.total_weight
      - if @order.received?
        %dt= t('shoppe.orders.build_time')
        %dd= distance_of_time_in_words(@order.created_at, @order.received_at)
      - if @order.invoiced?
        %dt= t('shoppe.orders.invoice_number')
        %dd= @order.invoice_number
      %dt= t('shoppe.orders.order_balance')
      %dd= boolean_tag @order.paid_in_full?, nil, :true_text => number_to_currency(@order.balance), :false_text => number_to_currency(@order.balance)
    - if @order.accepted? && !@order.shipped?
      = form_tag [:ship, @order] do
        %dl.form
          %dt.padding= label_tag 'consignment_number', t('shoppe.orders.consignment_number')
          %dd= text_field_tag 'consignment_number', '', :class => 'text'
        %dl.form
          %dd= submit_tag t('shoppe.orders.mark_as_shipped') , :class => 'button green button-mini'

    - unless @order.accepted? || @order.rejected?
      %dl.form
        %dd
          = link_to t('shoppe.orders.accept'), [:accept, @order], :method => :post, :class => 'button green'
          = link_to t('shoppe.orders.reject'), [:reject, @order], :method => :post, :class => 'button purple'

app/views/shoppe/orders/_order_items.html.haml
.order_items
  .table
    %table.data
      %thead
        %tr
          %th.qty= t('shoppe.orders.qty')
          %th= t('shoppe.orders.item')
          %th= t('shoppe.orders.sku')
          %th.money= t('shoppe.orders.cost')
          %th.money= t('shoppe.orders.price')
          %th.money= Shoppe.settings.tax_name
          %th.money= t('shoppe.orders.sub_total')
      %tbody
        - for item in @order.order_items
          %tr
            %td.qty= item.quantity
            %td.product
              = item.ordered_item.full_name
              %br
              - if !item.extra_info.blank?
                - for line in item.extra_info
                  = "- #{line}"
                  %br

            %td.sku= item.ordered_item.sku
            %td.money= number_to_currency item.total_cost
            %td.money= number_to_currency item.sub_total
            %td.money= number_to_currency item.tax_amount
            %td.money= number_to_currency item.total
        - if @order.delivery_service
          %td.qty
          %td.product= link_to @order.delivery_service.name, [:edit, @order.delivery_service]
          %td.sku
          %td.money= number_to_currency @order.delivery_cost_price
          %td.money= number_to_currency @order.delivery_price
          %td.money= number_to_currency @order.delivery_tax_amount
          %td.money= number_to_currency @order.delivery_price + @order.delivery_tax_amount
      %tfoot
        %tr
          %td.qty= @order.total_items
          %td{:colspan => 2}
          %td.money= number_to_currency @order.total_cost
          %td.money= number_to_currency @order.total_before_tax
          %td.money= number_to_currency @order.tax
          %td.money= number_to_currency @order.total

app/views/shoppe/orders/_payments_form.html.haml
= form_for [@order, Shoppe::Payment.new(:amount => @order.balance)] do |f|
  %dl.text
    %dt= f.label :method, t('shoppe.orders.method')
    %dd= f.text_field :method, :class => 'text'
  %dl.text
    %dt= f.label :reference, t('shoppe.orders.reference')
    %dd= f.text_field :reference, :class => 'text'
  %dl.amount
    %dt= f.label :amount, t('shoppe.orders.amount')
    %dd
      .moneyInput
        .currency= Shoppe.settings.currency_unit.html_safe
        = f.text_field :amount, :class => 'text'
  %dl.submit
    %dd= f.submit t('shoppe.orders.add_payment') , :class => 'button green'

app/views/shoppe/orders/_payments_table.html.haml
- unless @payments.empty?
  .table
    %table.data
      %thead
        %tr
          %th= t('shoppe.orders.id')
          %th= t('shoppe.orders.type')
          %th= t('shoppe.orders.method')
          %th= t('shoppe.orders.reference')
          %th= t('shoppe.orders.amount')
          %th= t('shoppe.orders.refunded?')
          %th
      %tbody
        - for payment in @payments
          %tr
            %td= payment.id
            %td
              = payment.refund? ? t('shoppe.orders.refund') : t('shoppe.orders.payment')
              %span.float-right= boolean_tag payment.confirmed?
            %td= payment.method
            %td= link_to_if payment.transaction_url, payment.reference, payment.transaction_url

            - if payment.refund?
              %td{:colspan => 2}
                %b= number_to_currency payment.amount
                - if payment.parent_payment_id
                  #{t('shoppe.orders.from_payment')} ##{payment.parent_payment_id}
            - else
              %td= number_to_currency payment.amount
              %td= boolean_tag payment.refunded?, nil, :true_text => number_to_currency(payment.amount_refunded)
            %td.refund
              - if payment.refundable?
                = link_to t('shoppe.orders.refund'), [:refund, @order, payment], :class => 'button purple button-mini', :rel => 'dialog'
              - else
                = link_to t('shoppe.delete'), [@order, payment], :class => 'button purple button-mini', :data => {:confirm => t('shoppe.orders.payment_remove_confirmation') }, :method => :delete
- else
  %p.notice= t('shoppe.orders.no_payments')

app/views/shoppe/orders/_search_form.html.haml
.orderSearch{:style => action_name == 'search' ? "display:block" : ''}
  = search_form_for @query, :url => search_orders_path, :html => { :method => :post } do |f|
    %dl.left
      %dt= f.label :id_eq, t('shoppe.orders.order_number')
      %dd= f.text_field :id_eq
      %dt= f.label :first_name_or_last_name_or_company_cont, t('shoppe.orders.customer')
      %dd= f.text_field :first_name_or_last_name_or_company_cont
      %dt= f.label :address1_or_address2_or_address3_or_address4_or_postcode_cont, t('shoppe.orders.billing_address')
      %dd= f.text_field :billing_address1_or_billing_address2_or_billing_address3_or_billing_address4_or_billing_postcode_cont
      %dt= f.label :consignment_number_cont, t('shoppe.orders.consignment_number')
      %dd= f.text_field :consignment_number_cont
      %dt= f.label :received_at_eq, t('shoppe.orders.received_between')
      %dd
        = f.text_field :received_at_gteq, :class => 'small'
        &rarr;
        = f.text_field :received_at_lteq, :class => 'small'
    %dl.right
      %dt= f.label :email_address_cont, t('shoppe.orders.email_address')
      %dd= f.text_field :email_address_cont
      %dt= f.label :phone_number_cont, t('shoppe.orders.phone_number')
      %dd= f.text_field :phone_number_cont
      %dt= f.label :status_eq, t('shoppe.orders.status')
      %dd= f.select :status_eq, [nil] + Shoppe::Order::STATUSES.map { |s| [t("shoppe.orders.statuses.#{s}"), s]}
      %dd= f.submit  t('shoppe.orders.search'), :class => 'button green button'